### PR TITLE
Adding listRunnerBook and listTimeRanges

### PR DESCRIPTION
**Pull request by Soccerama**
First pass for testing and comment. I've done some testing on each of these but it would be good to get feedback from others.

Addresses two points from issue #33.

### CODE REVIEW

**Comment by Soccerama** [comment]
Note that this now include the getAccountDetails function which is from issue #36. 

Meant to keep these separate but github had other ideas..

**Comment by Soccerama** [comment]
And listCurrencyRates from issue #36 is now also included in a new commit.

**Review by phillc73 — APPROVED** [review]
Looks good. Just some minor updates to the text in help, but I'll handle that later.

**Review by phillc73 — APPROVED** [review]
Also looks good, with the same minor updates to the help section. e.g. The example code includes getAccountDetails info.

**Pull request merged**
